### ISSUE TITLE
MessageSecurityException encountered during token refresh for on-premise claims

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/XrmCoreLibrary#16]
<b>maustinjones[CodePlex]</b> <br />MessageSecurityException encountered during token refresh for on-premise claims

at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData msgData, Int32 type)
at Microsoft.IdentityModel.Protocols.WSTrust.IWSTrustContract.Issue(Message message)
at Microsoft.IdentityModel.Protocols.WSTrust.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse rstr)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration1.Issue(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration1.AuthenticateFederationTokenInternal(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration1.Authenticate(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration.Authenticate(AuthenticationCredentials authenticationCredentials)
at Microsoft.Pfe.Xrm.XrmServiceManager2.RequestSecurityToken()
at Microsoft.Pfe.Xrm.XrmServiceManager2.GetProxyT
at Microsoft.Pfe.Xrm.XrmServiceManager2.GetProxy()

**Comment by seanmcne** [comment]
Resolved with changeset 35613: fix message security exception refreshing token. make auth type and service uri public prop getters. merge fixes/features to V5 branch.
